### ISSUE TITLE
Does openach works with European banks?

### ISSUE THREAD

**Issue by zenny** [openach/openach#3]
Just wondering whether openach works with European banks (SECA)?

Any pointers to European api?

Thanks and cheers,

**Comment by bobomurod** [comment]
This project looks like abandoned :(

**Comment by sbrendtro** [comment]
Apologies for the late response.  To your question on Euro payments... No, OpenACH doesn't support SEPA.  OpenACH is designed to process payments on the US Federal Reserve's FedACH network using the NACHA standard.  This is what banks in the United States use.  This project is still active, just very few code updates due to the unchanging nature of the NACHA formats.

**Comment by d-popov** [comment]
Any plans to support SEPA in the future?
